kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-jenkins-github-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: demodocker-jenkins-container
        image: 200.10.97.41/leo_hori/demo-jenkins-github:$BUILD_NUMBER
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-secret
