kind: Deployment
apiVersion: apps/v1
metadata:
  name: demodocker-jenkins-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: demodocker-jenkins-container
        image: 100.125.0.106:20202/leo_hori/demodocker-jenkins:$BUILD_NUMBER
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-secret
