kind: Service
apiVersion: v1
metadata:
  name: demodocker-jenkins-depl-service
  namespace: default
  selfLink: /api/v1/namespaces/default/services/demodocker-jenkins-depl-service
  uid: dc5cdac3-878d-4a86-a9d1-ff7d279ade1c
  labels:
    app: demodocker-jenkins-depl
    name: demodocker-jenkins-depl-service
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.health-check-flag: 'on'
    kubernetes.io/elb.health-check-option: '{"protocol":"TCP","delay":"5","timeout":"10","max_retries":"3"}'
    kubernetes.io/elb.id: f912cb4f-7a6e-4b45-8483-b45771eaaa34
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 81
      targetPort: 80
      nodePort: 30152
  selector:
    app: test
  clusterIP: 10.247.8.34
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 200.10.111.104
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 200.10.111.104
