version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_frontend_image:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp/repo/*
    steps:
      - checkout
      - run:
          name: Build Frontend image and push it to the SWR repo
          command: |
            TAG=1
            IMAGE=frontend
            DOCKERFILE=/$APP/$IMAGE/Dockerfile
            docker build -t $IMAGE:$TAG -f .$DOCKERFILE .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG

# Orchestrate our job run sequence
workflows:
  build_and_push:
    jobs:
      - build_frontend_image
context: guestbook