version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-image
          command: |
            TAG=1
            IMAGE=frontend
            DOCKER_REGISTRY=swr.la-south-2.myhuaweicloud.com
            DOCKER_REGISTRY_USER=la-south-2@D7LBOW4H1X356K7EA798
            DOCKER_REGISTRY_PASSWORD=68b251ee63b61e28f0488a616cf144e5d234db6957f6559839dbb6ffd4eb302d
            ORGANIZATION=garba-desarrollo
            PATH_APP=guestbook/frontend
            docker build -t $IMAGE:$TAG .
            docker build $PATH_APP -t $IMAGE:$TAG -f $PATH_APP/frontend/Dockerfile
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG