version: 2.1

jobs:
  build_frontend_image:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202010-01
    working_directory: /tmp/repo/*
    steps:
      - checkout
      - run:
          name: Build Frontend image and push it to the Huawei Cloud SWR repo
          command: |
            TAG=3
            IMAGE=frontend
            APP=guestbook
            DOCKERFILE=/$APP/$IMAGE/Dockerfile
            DOCKER_REGISTRY=swr.la-south-2.myhuaweicloud.com
            DOCKER_REGISTRY_USER=la-south-2@XHFAQQ88S48TMQXKZIGH
            DOCKER_REGISTRY_PASSWORD=5b31700488aab2a0543e997b56f004a3303a09022e878cf30476d8ddafe0eb28
            ORGANIZATION=garba-desarrollo
            docker build -t $IMAGE:$TAG -f .$DOCKERFILE .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG

  build_redis_master_image:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202010-01
    working_directory: /tmp/repo/*
    steps:
      - checkout
      - run:
          name: Build Redis Master image and push it to the Huawei Cloud SWR repo
          command: |
            TAG=3
            IMAGE=redis_master
            APP=guestbook
            DOCKERFILE=/$APP/$IMAGE/Dockerfile
            DOCKER_REGISTRY=swr.la-south-2.myhuaweicloud.com
            DOCKER_REGISTRY_USER=la-south-2@XHFAQQ88S48TMQXKZIGH
            DOCKER_REGISTRY_PASSWORD=5b31700488aab2a0543e997b56f004a3303a09022e878cf30476d8ddafe0eb28
            ORGANIZATION=garba-desarrollo
            docker build -t $IMAGE:$TAG -f .$DOCKERFILE .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG

  build_redis_slave_image:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202010-01
    working_directory: /tmp/repo/*
    steps:
      - checkout
      - run:
          name: Build Redis Slave image and push it to the Huawei Cloud SWR repo
          command: |
            TAG=3
            IMAGE=redis_slave
            APP=guestbook
            DOCKERFILE=/$APP/$IMAGE/Dockerfile
            DOCKER_REGISTRY=swr.la-south-2.myhuaweicloud.com
            DOCKER_REGISTRY_USER=la-south-2@XHFAQQ88S48TMQXKZIGH
            DOCKER_REGISTRY_PASSWORD=5b31700488aab2a0543e997b56f004a3303a09022e878cf30476d8ddafe0eb28
            ORGANIZATION=garba-desarrollo
            docker build -t $IMAGE:$TAG -f .$DOCKERFILE .
            docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$ORGANIZATION/$IMAGE:$TAG            
  deploy_to_kubernetes:
    docker:
      - image: swr.la-south-2.myhuaweicloud.com/garba-desarrollo/kubectl-garba:1
    working_directory: /tmp/repo/*
    steps:
      - checkout
      - run: sh ./deploy.sh
                  
workflows:
  build_push_deploy:
    jobs:
      - build_frontend_image
      - build_redis_master_image
      - build_redis_slave_image
      - deploy_to_kubernetes:
          requires:
          - build_frontend_image
          - build_redis_master_image
          - build_redis_slave_image
