apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: garba-desarrollo
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: redis-slave-container
        image: '100.125.3.34:20202/garba-desarrollo/redis_slave:${CIRCLE_SHA1}'
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
