apiVersion: v1
kind: Service
metadata:
  name: redis-slave-srv-2
  namespace: garba-desarrollo
  labels:
    app: redis
    tier: backend
    role: slave
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    tier: backend
    role: slave
