apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: garba-desarrollo
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: '100.125.3.34:20202/garba-desarrollo/frontend:IMAGE_TAG'
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
